acope3/RibModelFramework

- ribModel/src/Parameter.cpp
- ribModel/src/ROCParameter.cpp
- ribModel/src/include/base/Parameter.h
- ribModel/src/main.cpp
Parameter constructor now takes 1 arg, max AA size. Works fine with
normal sized array, with small array it works in debug mode, but not out
of debug mode.
> Got rid of hardcoded values in Parameter.cpp

- ribModel/src/FONSE/FONSETrace.cpp
- ribModel/src/Makefile
- ribModel/src/include/FONSE/FONSEModel.h
- ribModel/src/include/FONSE/FONSEParameter.h
- ribModel/src/include/FONSE/FONSETrace.h
> Uploaded FONSE headers and initial makefile

- ribModel/src/MCMCAlgorithm.cpp
- ribModel/src/Parameter.cpp
- ribModel/src/ROCModel.cpp
- ribModel/src/ROCParameter.cpp
- ribModel/src/include/FONSE/FONSEModel.h
- ribModel/src/include/RFP/RFPModel.h
- ribModel/src/include/ROC/ROCModel.h
- ribModel/src/include/ROC/ROCParameter.h
- ribModel/src/include/ROC/ROCTrace.h
- ribModel/src/include/base/Model.h
- ribModel/src/include/base/Parameter.h
- ribModel/src/main.cpp
With phi runs are currently broken
> Multiple Aphi/Sepsilon Update

- DevRscripts/runRFPModel.R
- ribModel/R/parameterObject.R
- ribModel/src/.idea/workspace.xml
See commit messages for more detail.
> Updated R documentation

- R/parameterObject.R
- R/plotTraceObject.R
- src/FONSEParameter.cpp
- src/RCPP_Parameter.cpp
- src/RCPP_Trace.cpp
- src/RFPParameter.cpp
- src/ROCParameter.cpp
- src/Trace.cpp
- src/include/FONSE/FONSEParameter.h
- src/include/base/Trace.h
- src/main.cpp
> General Fixes

- src/FONSEModel.cpp
- src/FONSEParameter.cpp
- src/MCMCAlgorithm.cpp
- src/Parameter.cpp
- src/RCPP_Parameter.cpp
- src/RCPP_Trace.cpp
- src/RFPModel.cpp
- src/RFPParameter.cpp
- src/ROCModel.cpp
- src/ROCParameter.cpp
- src/Trace.cpp
- src/include/FONSE/FONSEModel.h
- src/include/FONSE/FONSEParameter.h
- src/include/RFP/RFPModel.h
- src/include/RFP/RFPParameter.h
- src/include/ROC/ROCModel.h
- src/include/ROC/ROCParameter.h
- src/include/base/Model.h
- src/include/base/Parameter.h
- src/include/base/Trace.h
- src/main.cpp
I already merged Gabe's stuff so this should automatically merge.
> Name changes finished

- src/CodonTable.cpp
- src/CovarianceMatrix.cpp
- src/Gene.cpp
- src/Genome.cpp
- src/MCMCAlgorithm.cpp
- src/Parameter.cpp
- src/ROCModel.cpp
- src/ROCParameter.cpp
- src/SequenceSummary.cpp
- src/Testing.cpp
- src/Trace.cpp
- src/include/CodonTable.h
- src/include/CovarianceMatrix.h
- src/include/Utility.h
- src/include/base/Parameter.h
- src/main.cpp
Converted remainder print statements to new Utility.h format. Many minor style changes. Found and documented bug to be solved.
> Finished Utility.h implementation. Minor style changes.

- src/Model.cpp
- src/PANSEModel.cpp
- src/Parameter.cpp
- src/SequenceSummary.cpp
- src/Testing.cpp
- src/include/SequenceSummary.h
- src/main.cpp
- tests/testthat/testSequenceSummary.R
> test sequencesummary done

- src/FONSEModel.cpp
- src/FONSEParameter.cpp
- src/MCMCAlgorithm.cpp
- src/PANSEModel.cpp
- src/PANSEParameter.cpp
- src/Parameter.cpp
- src/RFPModel.cpp
- src/RFPParameter.cpp
- src/ROCParameter.cpp
- src/Testing.cpp
- src/Trace.cpp
- src/include/Genome.h
- src/include/MCMCAlgorithm.h
- src/include/Testing.h
- src/main.cpp
- tests/testthat/testMCMCAlgorithm.R
> cerr/cout -> my_print(Error)

- src/FONSEParameter.cpp
- src/PANSEParameter.cpp
- src/RFPParameter.cpp
Removed calls to exit from the mentioned parameter .cpp files in order
to remove the warnings in R
> Removed "Exits" from FONSE, PANSE and RFP

- src/FONSEModel.cpp
- src/ROCModel.cpp
Took documentation from ROC and added it to FONSE, making the necessary
changes. Also fixed a typo in the ROC documentation
> Added documentation from ROC to FONSE

- src/MCMCAlgorithm.cpp
- src/Parameter.cpp
- src/include/base/Parameter.h
I noticed that 6 arrays were being declared with new and deleted with
delete inside of a loop, so I made the change which has led to FONSE
being about 50% faster.
> Changed arrays to vectors

- src/MCMCAlgorithm.cpp
- src/Testing.cpp
- src/include/MCMCAlgorithm.h
- src/main.cpp
- tests/testthat/testMCMCAlgorithm.R
- tests/testthat/testMCMCROC.R
- tests/testthat/testRFPModel.R
Note: Passes R CMD check, currently not passing my own Travis CI builds.
> fixed unit testing errors

- src/FONSEParameter.cpp
- src/PANSEModel.cpp
- src/SequenceSummary.cpp
There were multiple loops that could have been condensed that I noticed and I went ahead and optimized them and tested the new version and they seem to be working properly. I also added documentation where I could and some TODOs
> FONSE model for loop optimizations and documentation

- README.md
- src/RCPP_Model.cpp
PA Simulate Genome bug squashed todo removed,
RCPP model PA build bug fixed
Updated README for syntax error
> Fixed bugs and edited README

- src/PANSEModelApprox.cpp
- src/include/PANSE/PANSEModelApprox.h
Hey Alex so to give you the approximations in the PANSE file creates a merge conflict since it changes the all the code for csp proposals. Instead I created a second file in the source and the include folder which you can test out by renaming.
> Acope3 master

- R/genomeObject.R
- R/mcmcObject.R
- R/modelObject.R
- R/parameterObject.R
Trying to remove ambiguities and make references to default settings more consistent.
> Minor improvements to R documentation

- R/mcmcObject.R
- src/MCMCAlgorithm.cpp
- src/ROCParameter.cpp
Hi Alex
I have just added a few lines of error message print out and make sure the program terminates when these fatal errors happen per Mike requested. I have tested that it should affect nothing but giving a few messages on the output, but let me know if I made a mistake.
Thanks
Lu
> added some error message and terminate the program

- R/parameterObject.R
Please use this one.  It has the fewest number of updates.
> Yet another attempt to fix bug in combineTwoDimensionalTrace

- R/parameterObject.R
> fixed 'end <- trace2' with 'end <- length(trace2)'.
